### ISSUE TITLE
Issue with IR remote control and Climate_IP

### ISSUE THREAD

**Issue by KameDomotics** [SebuZet/samsungrac#20]
Hi.
I have a issue, when I turn off the air conditioner (previously activated via climate_ip) from its physical remote control, in Home Assistant I always see the air conditioner on.
Any operation carried out by the Samsung remote IR control is not updated on the Home Assistant in lovelace.

Can you help me? Thanks

**Comment by KameDomotics** [comment]
Please nobody can help me?
This is my config:

```

climate:
  - platform: climate_ip
    name: Samsung AC   
    config_file: 'samsungrac.yaml'
    ip_address: '192.168.1.7'
    token: 'mytoken'
    cert: 'ac14k_m.pem'

```
